### ISSUE TITLE
Chaining and Rotation

### ISSUE THREAD

**Issue by JaredSartin** [playcanvas/playcanvas-tween#1]
Hey!

I am having LOADS of trouble with this. I have an object that I set a local rotation on (180 deg on the Y) and I want to do a "turn" tween (+/-20deg and then reverse it).

dir is either 1 or -1 to signify rotation.

`this.car.tween(this.car.getLocalRotation()).rotate({y: (20*dir)}, 0.1, pc.QuadraticInOut).yoyo(true).repeat(2).start();` will make the proper "turn" tween, but will start and end the car in the 0 Ydeg position, not the 180 Ydeg like previously set.

I then set out to do chaining, but the syntax is unclear. I want to do this: `this.car.tween(this.car.getLocalRotation()).rotate({y: (20*dir)}, 0.1, pc.QuadraticInOut).start();` followed by `this.car.tween(this.car.getLocalRotation()).rotate({y: (0)}, 0.2, pc.BackOut).start();`, the `.chain()` method doesn't seem to work well... What would the syntax look like for this?

**Comment by JaredSartin** [comment]
Current mess is:
```
      if(this.intoTurn || this.exitTurn) {
        this.intoTurn.stop();
        this.exitTurn.stop();
      }
      this.intoTurn = this.car.tween(this.car.getLocalEulerAngles()).rotate({y: (20*dir)}, 0.12, pc.QuadraticInOut);
      this.exitTurn = this.car.tween(this.car.getLocalEulerAngles()).rotate({y: (0*dir)}, 0.4, pc.BackOut);
      this.intoTurn.chain(this.exitTurn);
      this.intoTurn.start();
```

**Comment by daredevildave** [comment]
Looks like rotate expects euler angles not a quaternion. I'll take a look at fixing that soon.
