### ISSUE TITLE
Rotation only supports euler angles?

### ISSUE THREAD

**Issue by Leander1P** [playcanvas/playcanvas-tween#2]
This works (`getLocalEulerAngles` with `rotate`):

```
        obj.tween( obj.getLocalEulerAngles() )
            .rotate( dst.getLocalEulerAngles(), duration, pc.Linear )
            .start();
```

...and this does not work (`getLocalRotation` with `rotate`):

```
        obj.tween( obj.getLocalRotation() )
            .rotate( dst.getLocalRotation(), duration, pc.Linear )
            .start();
```

In our experiments the latter would result in rotation being effectively 0,0,0 at all times.

While it appears that the `rotate` function understands `pc.Quat`, the `start` function's `if (this._slerp)` clauses assume Euler angles when setting both `_fromQuat` and `_toQuat`.

It also seems that it may be desirable to skip the `// increment property` work entirely in `update` when `_this.slerp` is true, in favor of the later `this._quat.slerp` that happens just after.

(Might try to provide a PR for this at some point but we're on a heck of a deadline, and switching over to `getLocalEulerAngles` worked, so just leaving this issue here for now for anyone who trips over it.  May be related to some of the troubles expressed in issue #1.)

**Comment by daredevildave** [comment]
Yep, seems correct. I'll look into supporting quats too.

**Comment by yaustar** [comment]
There's a PR for this in https://github.com/playcanvas/playcanvas-tween/pull/22
