### ISSUE TITLE
Generate typescript definitions

### ISSUE THREAD

**Issue by yaustar** [playcanvas/playcanvas-tween#24]
This issue tracker is **only** for bug reports and feature requests. For general support/help, visit https://forum.playcanvas.com

For bug reports, include:

### Description

Provide as much information as possible. Include (where applicable):

* URL to a simple, reproducible test case that illustrates the problem clearly
* Screenshots
* The platform(s)/browser(s) where the issue is seen

### Steps to Reproduce

1.
2.
3.

**Comment by marcusx2** [comment]
Please this would be great!
