### ISSUE TITLE
options.element buggy?

### ISSUE THREAD

**Issue by ronkorving** [playcanvas/playcanvas-tween#5]
Hi there,

I was looking to use this library, and was just skimming through the code base. I noticed [this line](https://github.com/playcanvas/playcanvas-tween/blob/master/tween.js#L696) of code that I'm pretty sure is a bug. `options.element` is being passed in, but `element` (not `options.element`) is then used. It seems `element` is not even defined (I doubt this code passes a lint test).

So, someone (who actually uses this library already) will probably want to have a look at this?

Snippet:

```js
if (options && options.element) {
  // specifiy a element property to be updated
  tween.element = element; // <----- should this not be options.element?
}
```

**Comment by willeastcott** [comment]
Fixed in https://github.com/playcanvas/playcanvas-tween/commit/0d2b96b848789b765e275336ce49c38d28af8e53
